# Form implementation generated from reading ui file 'wform.ui'
#
# Created by: PyQt6 UI code generator 6.8.0.dev2410211537
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(800, 600)
        self.bloklyWebWidget = QtWidgets.QWidget(parent=mainWindow)
        self.bloklyWebWidget.setObjectName("bloklyWebWidget")
        mainWindow.setCentralWidget(self.bloklyWebWidget)
        self.menubar = QtWidgets.QMenuBar(parent=mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(parent=self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Settings = QtWidgets.QMenu(parent=self.menubar)
        self.menu_Settings.setObjectName("menu_Settings")
        self.menu_Controller = QtWidgets.QMenu(parent=self.menubar)
        self.menu_Controller.setObjectName("menu_Controller")
        self.menu = QtWidgets.QMenu(parent=self.menubar)
        self.menu.setObjectName("menu")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.action_Create = QtGui.QAction(parent=mainWindow)
        self.action_Create.setObjectName("action_Create")
        self.action_Open = QtGui.QAction(parent=mainWindow)
        self.action_Open.setObjectName("action_Open")
        self.action_Save = QtGui.QAction(parent=mainWindow)
        self.action_Save.setObjectName("action_Save")
        self.action_SaveAs = QtGui.QAction(parent=mainWindow)
        self.action_SaveAs.setObjectName("action_SaveAs")
        self.action_Build = QtGui.QAction(parent=mainWindow)
        self.action_Build.setObjectName("action_Build")
        self.action_2 = QtGui.QAction(parent=mainWindow)
        self.action_2.setObjectName("action_2")
        self.action_Upload = QtGui.QAction(parent=mainWindow)
        self.action_Upload.setObjectName("action_Upload")
        self.menu_File.addAction(self.action_Create)
        self.menu_File.addAction(self.action_Open)
        self.menu_File.addAction(self.action_Save)
        self.menu_File.addAction(self.action_SaveAs)
        self.menu_Controller.addAction(self.action_Build)
        self.menu_Controller.addAction(self.action_Upload)
        self.menu.addAction(self.action_2)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Settings.menuAction())
        self.menubar.addAction(self.menu_Controller.menuAction())
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "IDR Rudion Visual IDE"))
        self.menu_File.setTitle(_translate("mainWindow", "Фаил"))
        self.menu_Settings.setTitle(_translate("mainWindow", "Настройки"))
        self.menu_Controller.setTitle(_translate("mainWindow", "Контроллер"))
        self.menu.setTitle(_translate("mainWindow", "Помощь"))
        self.action_Create.setText(_translate("mainWindow", "Создать новый"))
        self.action_Open.setText(_translate("mainWindow", "Открыть"))
        self.action_Save.setText(_translate("mainWindow", "Сохрвнить"))
        self.action_SaveAs.setText(_translate("mainWindow", "Сохранить как"))
        self.action_Build.setText(_translate("mainWindow", "Собрать"))
        self.action_2.setText(_translate("mainWindow", "Спросить у ИИ"))
        self.action_Upload.setText(_translate("mainWindow", "Прошить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec())
